### ISSUE TITLE
Ucieczka z githuba

### ISSUE THREAD

**Issue by DestroTM** [kuba1569/vacationProject#2]
Proponuję przejście na inny hosting niż github. Na wersji free tutaj dużo nie podziałamy, chyba że chcecie open-source klepać.
Dodawanie pomysłów na projekty też chyba lepiej realizować innym miejscu, bo szkoda żeby miały one okazje do zostania przechwyconymi przez innych developerów bez pomysłów.
Bitbucket wraz z rozrastaniem się teamu niestety też zaczyna kosztować.

Proponuję wobec tego trzymać kody na repo na **GitLab**.
W razie znalezienia lepszej alternatywy, Git nie będzie robił problemów z przeprowadzką.

**Comment by gtwsky** [comment]
skoro tak, to załóż repo na gitlabie i podaj linka nizej :)

**Comment by kuba1569** [comment]
Projekt zaimportowałem więc zachowało się to co pisaliście. Ofc jest ustawiony na prywatny więc nikt sam się nie doda. Dodałem wstępnie Adama, bo ma tam konto natomiast Michał stwórz sobie konto to Cię dodam.
https://gitlab.com/kuba1569/vacationProject/
